services:
  postulaciones_nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: postulaciones_nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postulaciones_db
      - postulaciones_app
    networks:
      - kuali_network
  postulaciones_db:
    image: mysql:latest
    container_name: postulaciones_db
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: postulaciones
      MYSQL_USER: postulaciones
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - kuali_network
  postulaciones_app:
    container_name: postulaciones_app
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - kuali_network
  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - kuali_network
  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html
    networks:
      - kuali_network
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postulaciones_db
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - kuali_network
  pint: 
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/vendor/bin/pint"]
    networks:
      - kuali_network

networks:
  kuali_network:
    external: true